#!/bin/bash
if [ "$#" == 0 ]
then
  docker run --name=web --volume=/vagrant:/project --tty=false --interactive=false --detach=true web
else
  docker run --name=web_run --volume=/vagrant:/project --tty=true --interactive=true --detach=false --rm=true web $@
fi
